<!DOCTYPE><html>
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge;" />
    <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="<?php echo WEB_ROOT;?>/javascripts/utils.js" ></script>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
    <!--<script type="text/javascript" src="<?php echo WEB_ROOT;?>/javascripts/jstree.min.js" ></script>--></script>

	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css" rel="stylesheet">
    <link rel="stylesheet" href="http://v4-alpha.getbootstrap.com/assets/css/docs.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/custom.css">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/collapse.css">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/font-awesome.min.css">



</head>
<body>
<div class="container">
    <a href="/"><img class="header_banniere" src="/images/bandeau_fixe.jpg" /></a>
    <?php if(Utils::getCurrentUser()){
        echo '<a href="'.Utils::getConf()['security']['urllogout'].'">Déconnexion</a>';
    } ?>
	<?php include('menu.phtml');?>

    <?php
        $msgs = Utils::getMsg(Utils::NOTICE_MSG);
        $class= count($msg) ? 'show' : 'hide';
    ?>
    <div id="div_msg_notice" class="alert alert-notice <?php echo $class; ?> ">
        <a href="#anchor_notice"></a>
        <div id="msg_notice">
        <?php
        if(count($msgs)>0) {
            foreach ($msgs as $mess) {
                echo $mess.'<br>';
            }
        }
        ?>
        </div>
    </div>
    <?php
        $msgs = Utils::getMsg(Utils::SUCCESS_MSG);
        $class= count($msg) ? 'show' : 'hide';
    ?>
    <div id="div_msg_success" class="alert alert-success  <?php echo $class; ?> "><strong>Félicitations !</strong>
        <div id="msg_success">
        <?php
        if(count($msgs)>0) {
            foreach ($msgs as $mess) {
                echo $mess."<br>";
            }
        }
        ?>
        </div>
    </div>

    <?php
        $msgs = Utils::getMsg(Utils::FAIL_MSG);
        $class= count($msg) ? 'show' : 'hide';
    ?>
    <div id="div_msg_fail" class="alert alert-danger  <?php echo $class; ?>"><strong>Erreur !</strong>
        <a href="#anchor_fail"></a>
        <div id="msg_fail" >
        <?php
        if(count($msgs)>0) {
            foreach ($msgs as $mess) {
                echo $mess.'<br>';
            }
        }
        ?>
        </div>
    </div>
    <?php
    Utils::resetMsg();

    ?>

    <?php echo $this->content(); ?>
    <?php //include('footer.phtml');?>
</div>
</body>
</html>