<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo WEB_ROOT; ?>/listuser">Liste des utilisateurs</a>
            <a class="navbar-brand" href="<?php echo WEB_ROOT; ?>/createuser">Ajouter un utilisateur</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>